### ISSUE TITLE
namespaces not resolved in yaml

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_k8s#175]
error message from bazel run :deploy_dev.create:
```
Error from server (NotFound): error when creating "STDIN": namespaces "brian" not found
Error from server (NotFound): error when creating "STDIN": namespaces "brian" not found
```

the namespace is never properly resolved in the yaml printed to STDOUT on bazel run :deploy_dev. The image name is resolved as expected.

I also tried setting `namespace: default` in the yaml. the yaml printed to STDOUT on bazel run :deploy_dev still just has the default namespace, and running bazel run :deploy_dev.create errors out with:
```
the namespace from the provided object "default" does not match the namespace "brian". You must pass '--namespace=default' to perform this operation.
the namespace from the provided object "default" does not match the namespace "brian". You must pass '--namespace=default' to perform this operation.
```

WORKSPACE:
```
k8s_defaults(
        name = "k8s_deploy_dev",
        namespace = "{BUILD_USER}",
        cluster = "foo",
        image_chroot = "bar"
)
```

BUILD:
```
load("@io_bazel_rules_docker//go:image.bzl", "go_image")
load("@k8s_deploy_dev//:defaults.bzl", "k8s_deploy_dev")

k8s_deploy_dev(
        name = "deploy_dev",
        template = ":k8s.yaml",
        images = { 
                "webserver-dev": ":server"
        },  

)

go_image(
        name = "server",
        srcs = [ 
                "main.go",
        ],  
        deps = [ 
                "@org_golang_x_crypto//bcrypt:go_default_library",
        ],  
        goarch = "amd64",
        goos = "linux",
        pure = "on",
        visibility = ["//visibility:public"],
)
```

YAML:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: webserver-dev
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP 
---
kind: Service
apiVersion: v1
metadata:
  name: pipeline
spec:
  selector:
    app: pipeline
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
  type: LoadBalancer
```
