### ISSUE TITLE
delete does not call custom resolver / resolver at all

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_k8s#182]
Thank you for your great rules.

I found problems with "*.delete" rule.
Unfortunately, resolver / customer resolver is not used on "delete".

I have following template:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: <NAMESPACE>
...
```
And it can not be deleted by k8s rules.

So, would be great to call resolver on delete as well.

I know about k8s_defaults, but it is not suitable for me.

I have different k8s stands, like:
1. Personal Development stand (namespace name calculated based on AWS caller identity + git branch name)
2. Production stand (namespace fixed)

Right now I have the same rules for create k8s_object, and I am changing only resolver_args for my wrapper.

As result, first stand run with namespace like "oleg-tsarev-my_git_branch_name" and production with "production-project-name".

So, I forced to describe two different so different configuration, where the single difference - namespace name.

If you will fix resolver behaviour, I can use the same rules, and just change resolver.

**Comment by nlopezgi** [comment]
Hi @excavador and thanks for using rules_k8s.
iiuc your issue, I think it should be feasible to call the resolver on delete, but its just not being done atm as we had not seen this type of use case before. We have a bit of a backlog of work atm. It would be awesome if you could try creating a PR to address this issue! Otherwise I'll add it to the backlog and will keep you up to date when we have time to address this.

@fejta to see if he has any thoughts about possible issues related to calling the resolver on delete.

**Comment by nhyne** [comment]
Hey @nlopezgi do you know if anyone has made any progress on this? If not I may give a PR a try.

**Comment by AmandaCameron** [comment]
Because of this issue, I can't use these rules to clean up a k8s deployment, as to make sure devs and prod don't clash, I name my kubernetes resources using this. For example: 

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-service-%{release-name}
  labels:
    app: example-service
    release: "%{release-name}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-service
        release: "%{release-name}"
    spec:
      containers:
        - name: example-service
          image: example:do_not_delete
          args:
          - -some-arg=%{es-some-arg}
          - -some-other-arg=%{es-some-other-arg}
```

then I'll have something like this for the BUILD:

```python
k8s_dev_deploy(
  name = "k8s-dev-deploy",
  images = {
    "example:do_not_delete": ":docker-image",
  },
  substitutions = {
    "%{release-name}": "dev-$(BUILD_USER)",
  },
  template = ":deployment.yaml",
)
```
