### ISSUE TITLE
Rule will not cleanup PVC correctly

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#259]
Here are the steps to recreate 

1. Use rules to install a stateful set with a PV that is dynamically provisioned
1. Use bazel to apply target
1. Use bazel to delete target

The PVC, PV and disk will still exist. Bazel and kubectl delete do not know about stateful sets and dynamically provisioned volumes.

https://kubernetes.io/docs/tasks/run-application/delete-stateful-set/#complete-deletion-of-a-statefulset

We need to determine how we want to handle this.

**Comment by nlopezgi** [comment]
I think the best place to start is to get your steps to recreate as an e2e test so we can see what additional commands we would need to run to delete the stateful set, once we have that we can fix the delete rule to integrate the new commands to delete the stateful set.
Do you know how critical is support for this feature so we can prioritize?
Do you want to volunteer to implement the e2e test?

**Comment by chrislovecnm** [comment]
To add some background.

```yaml
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: standard
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: "2Gi"
```
Within a Stateful Set a user is able to define `volumeClaimTemplates`.  This template automatically creates PV, PVCs, and often cloud drives.  These volumes are independent Objects that are not owned by the Stateful Set.  When the Stateful Set is deleted the PV, PVCs and cloud volumes are left in place.  This is _as designed_, but requires cleanup.  

I think having an optional value for k8s_rules to cleanup the PVs and PVCs would be an idea.
