### ISSUE TITLE
Unable to use delete script when substitution done in the name of K8s object

### ISSUE THREAD

**Issue by diegohavenstein** [bazelbuild/rules_k8s#556]
I am having issues with the `.delete` script on a K8s job using a substitution as part of its name.

The issue can be reproduced with other K8s abstractions (e.g. deployment). Here is a minimum example to reproduce the issue:

1. Put the files below in a dir and run `bazel run jobfile_k8s_objects.create`.
2. You'll see the `pi-whatever` job running to completion, as we are using `name: pi-{job-name}` and `substitutions = {"{job-name}" : "whatever"}`.
3. Try to remove the job again by `bazel run jobfile_k8s_objects.delete`. This will not remove the job. It will also not fail (due to `--ignore-not-found=true`?)

This problem does NOT arise if no substitutions are part of the object name, e.g. if we used instead `name: pi` and `substitutions = {}`

Please let me know if I am doing something wrong here, or whether this is a known issue.

BUILD:
```
load(":job.bzl", "k8s_config")
config = k8s_config(name = "jobfile")
```

job.bzl:
```
load("@io_bazel_rules_k8s//k8s:object.bzl", "k8s_object")
load("@io_bazel_rules_k8s//k8s:objects.bzl", "k8s_objects")

def k8s_config(name):
    k8s_object(name=name + "_k8s_object",
               kind = "job",
               template = "job.yaml",
               substitutions = {"{job-name}" : "whatever"},
               cluster = "minikube",
               context = "minikube",
               namespace = "default",
               image_chroot = "",
               images = {})
    k8s_objects_name = name + "_k8s_objects"
    k8s_objects(name=k8s_objects_name,
                objects = [name + "_k8s_object"])
```

job.yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-{job-name}
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_k8s",
    sha256 = "cc75cf0d86312e1327d226e980efd3599704e01099b58b3c2fc4efe5e321fcd9",
    strip_prefix = "rules_k8s-0.3.1",
    urls = ["https://github.com/bazelbuild/rules_k8s/releases/download/v0.3.1/rules_k8s-v0.3.1.tar.gz"],
)

load("@io_bazel_rules_k8s//k8s:k8s.bzl", "k8s_repositories")
k8s_repositories()

load("@io_bazel_rules_k8s//k8s:k8s_go_deps.bzl", k8s_go_deps = "deps")
k8s_go_deps()
```
