### ISSUE TITLE
Substitutions in k8s_object does not work. :(

### ISSUE THREAD

**Issue by asiekkowa** [bazelbuild/rules_k8s#562]
Substitutions in k8s_object does not work. :(

Tested yaml file:
```yaml
kind: %{RESOURCE_TYPE}                                                                                                                                                   
apiVersion: argoproj.io/v1alpha1
metadata:
  name: test
  generateName: test-e2e
spec:
  arguments:
    parameters:
...
```

BUILD.bazel file:
```
load("@io_bazel_rules_k8s//k8s:object.bzl", "k8s_object")                                                                                                                
  
images = {
...
}

k8s_object(
    name = "workflow.template",
    kind = "workflowtemplate",
    template = "workflow.template.yaml",
    images = images,
    substitutions = {
        "%{RESOURCE_TYPE}": "WorkflowTemplate",
    },
    cluster = "XYZ",
)
k8s_object(
    name = "workflow",
    kind = "workflow",
    template = "workflow.template.yaml",
    images = images,
    substitutions = {
        "%{RESOURCE_TYPE}": "Workflow",
    },
    cluster = "XYZ",
)
```

Output of command
```
bazel run :workflow
``` 
is correct, variable RESOURCE_TYPE is being replaced.

Unfortunately when I try to run:
```
bazel run :workflow.delete #(or .create)
``` 
I got:
```
  File "/home/abc/.cache/bazel/_bazel_abc/c27b7a4375a4d9fe604f9c7388818c81/execroot/__main__/bazel-out/k8-fastbuild/bin/workflow.delete.runfiles/com_github_yaml_pyyaml/lib3/yaml/scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "<unicode string>", line 1, column 7:
    kind: %{RESOURCE_TYPE}
```

tested bazel versions:
- 1.2.1
- 3.1.0
